version: '3.7'

services:
  api-gateway:
    build:
      dockerfile: ./services/api-gateway/dev.dockerfile
      context: .
    volumes:
      - ./services/api-gateway/config.dev.yaml:/config/config.yaml
    ports:
      - 7000:80

  controller.switch:
    build:
      dockerfile: ./dockerfiles/dev.node.dockerfile
      context: .
      args:
        service_name: controller.switch
    volumes:
      - ./services/controller.switch:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 7001:80

  discord:
    build:
      dockerfile: ./dockerfiles/dev.node.dockerfile
      context: .
      args:
        service_name: discord
    volumes:
      - ./services/discord:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 7002:80
    env_file:
      - ./services/discord/.env

  spotify:
    build:
      dockerfile: ./dockerfiles/dev.node.dockerfile
      context: .
      args:
        service_name: spotify
    volumes:
      - ./services/spotify:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 7003:80
    env_file:
      - ./services/spotify/.env

  scheduler:
    build:
      dockerfile: ./dockerfiles/dev.node.dockerfile
      context: .
      args:
        service_name: scheduler
    volumes:
      - ./services/scheduler:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 7004:80

  cron.scheduler-tick:
    build:
      dockerfile: ./services/cron.scheduler-tick/dev.dockerfile
      context: .
    volumes:
      - ./services/cron.scheduler-tick/script.sh:/script.sh
