version: '3.7'

services:
  api-gateway:
    build:
      dockerfile: ./services/api-gateway/prod.dockerfile
      context: .
    volumes:
      - ./services/api-gateway/config.prod.yaml:/config/config.yaml
    ports:
      - 7000:80

  service.controller.switch:
    build:
      dockerfile: ./services/controller.switch/dev.dockerfile
      context: .
    volumes:
      - ./services/controller.switch:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 7001:3000
    environment:
      NODE_ENV: development

  service.discord:
    build:
      dockerfile: ./services/discord/dev.dockerfile
      context: .
    volumes:
      - ./services/discord:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 7002:3000
    env_file:
      - ./services/discord/.env
    environment:
      NODE_ENV: development

  service.spotify:
    build:
      dockerfile: ./services/spotify/dev.dockerfile
      context: .
    volumes:
      - ./services/spotify:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 7003:3000
    env_file:
      - ./services/spotify/.env
    environment:
      NODE_ENV: development

  service.scheduler:
    build:
      dockerfile: ./services/scheduler/dev.dockerfile
      context: .
    volumes:
      - ./services/scheduler:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 7004:3000
    environment:
      NODE_ENV: development

  cron.scheduler-tick:
    build:
      dockerfile: ./services/cron.scheduler-tick/dev.dockerfile
      context: .
    volumes:
      - ./services/cron.scheduler-tick/script.sh:/script.sh
