apis:
  service.controller.switch:
    name: Switch Controller
    prefix: service.controller.switch
    upstream_url: http://service.controller.switch
    allow_cross_origin: true
    plugins:
      - name: retry
        enabled: true
        config:
          attempts: 1
