apis:
  service.controller.switch:
    name: Switch Controller
    prefix: controller.switch
    upstream_url: http://192.168.0.19:7001
    allow_cross_origin: true
    plugins:
      - name: retry
        enabled: true
        config:
          attempts: 3
  service.discord:
    name: Discord Service
    prefix: discord
    upstream_url: http://192.168.0.19:7002
    allow_cross_origin: false
    plugins:
      - name: retry
        enabled: true
        config:
          attempts: 3
  service.spotify:
    name: Spotify Service
    prefix: spotify
    upstream_url: http://192.168.0.19:7003
    allow_cross_origin: false
    plugins:
      - name: retry
        enabled: true
        config:
          attempts: 3
